name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Caching Pip Dependencies
        uses: actions/cache@v3
        with:
            path: |
              ~/.cache/pip
              .dvc/cache
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('.dvc/config') }}
            restore-keys: |
              ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              ${{ runner.os }}-pip-
              ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro

      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py
